"""Initial migration

Revision ID: d6332f673338
Revises: 
Create Date: 2024-03-02 20:04:04.600560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6332f673338'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contests',
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('finish_time', sa.String(), nullable=False),
    sa.Column('A_st', sa.String(), nullable=True),
    sa.Column('A_flc', sa.Integer(), nullable=True),
    sa.Column('B_st', sa.String(), nullable=True),
    sa.Column('B_flc', sa.Integer(), nullable=True),
    sa.Column('C_st', sa.String(), nullable=True),
    sa.Column('C_flc', sa.Integer(), nullable=True),
    sa.Column('D_st', sa.String(), nullable=True),
    sa.Column('D_flc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contests')
    # ### end Alembic commands ###
